var hl_3 = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78493000000002, -7.339759999999991, 0] },
      properties: {
        fid: 1,
        Name: "Halte Gunung Anyar Timur 2",
        descriptio: "After this stop, the bus will continue the journey northward (to Kenjeran). You can keep on board.",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78464, -7.339919999999992, 0] },
      properties: {
        fid: 2,
        Name: "Halte Gunung Anyar Timur 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78158, -7.333980000000001, 0] },
      properties: {
        fid: 3,
        Name: "Halte Gunung Anyar Lor 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78134, -7.334140000000003, 0] },
      properties: {
        fid: 4,
        Name: "Halte Gunung Anyar Lor 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78096, -7.331010000000007, 0] },
      properties: {
        fid: 5,
        Name: "Halte Rungkut Madya 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78142, -7.330240000000002, 0] },
      properties: {
        fid: 6,
        Name: "Halte Rungkut Madya 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78155, -7.3266799999999925, 0] },
      properties: {
        fid: 7,
        Name: "Halte Penjaringan Asri",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78086, -7.321899999999991, 0] },
      properties: {
        fid: 8,
        Name: "Halte Pandugo 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.781181, -7.321934000000005, 0] },
      properties: {
        fid: 9,
        Name: "Halte Pandugo 2",
        descriptio: "Mr. Sumo, Dunia Steak, Masjid At-Tanwiir, Rusun Penjaringan Sari",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.780745, -7.31191000000001, 0] },
      properties: {
        fid: 10,
        Name: "Halte Dinamika",
        descriptio: "Universitas Dinamika (STIKOM), Apartemen Gunawangsa MERR, Superindo",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78109, -7.3057599999999905, 0] },
      properties: {
        fid: 11,
        Name: "Halte Semampir",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78064, -7.306069999999998, 0] },
      properties: {
        fid: 12,
        Name: "Halte Sentra UKM Merr",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78155, -7.300599999999996, 0] },
      properties: {
        fid: 13,
        Name: "Halte Semolowaru 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78178, -7.3017300000000045, 0] },
      properties: {
        fid: 14,
        Name: "Halte Semolowaru 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78042000000002, -7.2913700000000015, 0] },
      properties: {
        fid: 15,
        Name: "Halte ITATS",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78082, -7.29152000000001, 0] },
      properties: {
        fid: 16,
        Name: "Halte Universitas Katolik Darma Cendika",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.780425, -7.2892549999999945, 0] },
      properties: {
        fid: 17,
        Name: "Halte Park and Ride Arief Rahman Hakim",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78052, -7.288629999999998, 0] },
      properties: {
        fid: 18,
        Name: "Halte SMPN 19",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78085, -7.28855, 0] },
      properties: {
        fid: 19,
        Name: "Halte Kopertis",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78074, -7.284260000000001, 0] },
      properties: {
        fid: 20,
        Name: "Halte RS Haji 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.781, -7.28237999999999, 0] },
      properties: {
        fid: 21,
        Name: "Halte RS Haji 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78194, -7.280249999999997, 0] },
      properties: {
        fid: 22,
        Name: "Halte Kertajaya Indah",
        descriptio:
          "One East Apartment.<br><br>Service available:<br>1. Trans Semanggi (TB-II) bound for ITS & Kejawan Putih<br>2. Suroboyo Bus MERR (R5) bound for Kenjeran<br>3. Suroboyo Bus MERR (R6) bound for Gunung Anyar",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78247, -7.280555000000007, 0] },
      properties: {
        fid: 23,
        Name: "Halte Kertajaya Indah 2 (Halte Manyar Kertoadi)",
        descriptio:
          "This is the new stop, as of 12 August 2022.<br><br>Available services:<br>1. Suroboyo Bus MERR (R5) bound for Kenjeran<br>2. Suroboyo Bus MERR (R6) bound for Gunung Anyar<br><br>Please change here for Trans Semanggi (TB-II) bound for Lidah Wetan.<br><br>",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.79000300000001, -7.279520000000004, 0] },
      properties: {
        fid: 24,
        Name: "Halte ITS",
        descriptio:
          "Institut Teknologi Sepuluh Nopember, Sukolilo Campus.<br><br>Service available:<br>1. Trans Semanggi (TB-II) bound for UNESA & SPBU Lidah Wetan<br>2. Suroboyo Bus MERR (R5) bound for Kenjeran<br>3. Suroboyo Bus MERR (R6) bound for Gunung Anyar",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78073, -7.279549999999992, 0] },
      properties: {
        fid: 25,
        Name: "Halte KONI MERR",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78109, -7.2762200000000075, 0] },
      properties: {
        fid: 26,
        Name: "Halte Galaxy",
        descriptio: "Galaxy Mall 3, One Galaxy Apartment",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78158, -7.275709999999997, 0] },
      properties: {
        fid: 27,
        Name: "Halte Galaxy",
        descriptio: "Galaxy Mall 1 & 2 (Sogo)",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78214, -7.269147999999994, 0] },
      properties: {
        fid: 28,
        Name: "Halte Unair 1",
        descriptio: "Universitas Airlangga Kampus C",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.782441, -7.269259999999998, 0] },
      properties: {
        fid: 29,
        Name: "Halte Unair 2",
        descriptio: "Universitas Airlangga Kampus C",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.782736, -7.262251999999992, 0] },
      properties: {
        fid: 30,
        Name: "Halte Mulyorejo",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.783234, -7.264061000000003, 0] },
      properties: {
        fid: 31,
        Name: "Halte Mulyorejo 2",
        descriptio: "Airlangga Convention Center, Universitas Airlangga Kampus C",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78241400000002, -7.254434000000004, 0] },
      properties: {
        fid: 32,
        Name: "Halte Kalijudan",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.782398, -7.255998999999992, 0] },
      properties: {
        fid: 33,
        Name: "Halte Kalijudan 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.78354600000002, -7.25140599999999, 0] },
      properties: {
        fid: 34,
        Name: "Halte RSIA 1",
        descriptio: "RSIA Kendangsari MERR",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.783932, -7.251241000000003, 0] },
      properties: {
        fid: 35,
        Name: "Halte RSIA 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.791384, -7.252015000000001, 0] },
      properties: {
        fid: 36,
        Name: "Halte Superindo",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.793041, -7.252071999999992, 0] },
      properties: {
        fid: 37,
        Name: "Halte Kenjeran",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.796098, -7.252737000000001, 0] },
      properties: {
        fid: 38,
        Name: "Halte Kenpark",
        descriptio: "Kenjeran Park",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
  ],
};
