var hl_4 = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7362725, -7.298965700000005, 0] },
      properties: {
        fid: 1,
        Name: "Terminal Intermoda Joyoboyo",
        descriptio:
          "Service available:<br>1. R1 Suroboyo Bus bound for Rajawali<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jl. Jono Soewojo/Bukit Darmo Blvd.)<br><br>Terminal Intermoda Joyoboyo serves as the Terminus Stop for Lin 4 Suroboyo Bus (Joyoboyo - Jono Soewojo)",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7263115, -7.302967299999994, 0] },
      properties: {
        fid: 2,
        Name: "Halte Rusun Gunungsari 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7265382, -7.3023233999999935, 0] },
      properties: {
        fid: 3,
        Name: "Halte Rusun Gunungsari 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.723684, -7.30619859999999, 0] },
      properties: {
        fid: 4,
        Name: "Halte Pasar Ikan 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.72412370000002, -7.305638200000008, 0] },
      properties: {
        fid: 5,
        Name: "Halte Pasar Ikan 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7098825, -7.311854000000001, 0] },
      properties: {
        fid: 6,
        Name: "Halte Mastrip 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.71038950000002, -7.311372499999995, 0] },
      properties: {
        fid: 7,
        Name: "Halte Mastrip 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.708416, -7.312867999999992, 0] },
      properties: {
        fid: 8,
        Name: "Halte Gogor 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.708392, -7.312609000000003, 0] },
      properties: {
        fid: 9,
        Name: "Halte Gogor 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7045035, -7.3131665999999935, 0] },
      properties: {
        fid: 10,
        Name: "Halte Gemol 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7046832, -7.312948400000005, 0] },
      properties: {
        fid: 11,
        Name: "Halte Gemol 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7003498, -7.313775700000001, 0] },
      properties: {
        fid: 12,
        Name: "Universitas Wijaya Putra",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7008138, -7.313512400000009, 0] },
      properties: {
        fid: 13,
        Name: "Halte Keramat",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6950825, -7.314048200000006, 0] },
      properties: {
        fid: 14,
        Name: "Halte Kecamatan Wiyung 1",
        descriptio: "Kantor Kecamatan Wiyung",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.695112, -7.313795499999999, 0] },
      properties: {
        fid: 15,
        Name: "Halte Kecamatan Wiyung 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.690653, -7.313022099999996, 0] },
      properties: {
        fid: 16,
        Name: "Halte Taman Mozaik 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6906476, -7.312742799999992, 0] },
      properties: {
        fid: 17,
        Name: "Halte Taman Mozaik 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6868382, -7.3115901999999995, 0] },
      properties: {
        fid: 18,
        Name: "Halte Pondok Rosan 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6875342, -7.311477099999997, 0] },
      properties: {
        fid: 19,
        Name: "Halte Pondok Rosan 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6829784, -7.310935, 0] },
      properties: {
        fid: 20,
        Name: "Halte Graha Sampoerna Indah",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6832681, -7.310748799999995, 0] },
      properties: {
        fid: 21,
        Name: "Halte Dukuh Karangan",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6763373, -7.309622299999991, 0] },
      properties: {
        fid: 22,
        Name: "Halte Griya Babatan Mukti 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67660550000001, -7.309404199999993, 0] },
      properties: {
        fid: 23,
        Name: "Halte Griya Babatan Mukti 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6742106, -7.306753300000003, 0] },
      properties: {
        fid: 24,
        Name: "Halte Babatan 1",
        descriptio:
          "Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6744107, -7.306761600000001, 0] },
      properties: {
        fid: 25,
        Name: "Halte Babatan 2",
        descriptio: "Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6753578, -7.298334300000003, 0] },
      properties: {
        fid: 26,
        Name: "Halte UNESA",
        descriptio:
          "Universitas Negeri Surabaya, CitraLand Gate, National Hospital.<br>Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67571380000001, -7.298327600000009, 0] },
      properties: {
        fid: 27,
        Name: "Halte UNESA 2",
        descriptio:
          "Universitas Negeri Surabaya, CitraLand Gate, National Hospital, Blvd. Famili Selatan.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R8",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.675693, -7.292597899999993, 0] },
      properties: {
        fid: 28,
        Name: "Halte Graha Famili 1",
        descriptio:
          "Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo) stops here.<",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67608, -7.2927500000000105, 0] },
      properties: {
        fid: 29,
        Name: "Halte Graha Famili 2",
        descriptio:
          "Plaza Graha Famili, Loop, Sekolah Petra 1.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67723000000001, -7.288350000000002, 0] },
      properties: {
        fid: 30,
        Name: "Halte PTC",
        descriptio:
          "Pakuwon Mall, PTC, Spazio.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for Lenmarc (Jono Soewojo)",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6776844, -7.288790400000004, 0] },
      properties: {
        fid: 31,
        Name: "Halte PTC 2",
        descriptio:
          "Spazio, PTC, Pakuwon Mall.<br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo<br><br>IMPORTANT NOTICE: <br>As of 12 August 2022, R8 Suroboyo Bus bound for Joyoboyo stops here.<br>You can trans",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.68105, -7.284729999999998, 0] },
      properties: {
        fid: 32,
        Name: "Halte Jono Soewojo",
        descriptio:
          "Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus (Last stop). After this stop the bus will be continued to be R8 bound for Joyoboyo. You can stay on board.",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6813879, -7.284939799999993, 0] },
      properties: {
        fid: 33,
        Name: "Halte Jono Soewojo 2",
        descriptio:
          "Lenmarc Mall, Bukit Darmo Golf, Adhiwangsa Apartment.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7394435, -7.29615480000001, 0] },
      properties: {
        fid: 34,
        Name: "Halte Marmoyo",
        descriptio: "Service available:<br>1. R2 Suroboyo Bus bound for Purabaya<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.73785, -7.298909999999996, 0] },
      properties: {
        fid: 35,
        Name: "Halte Joyoboyo 2",
        descriptio: "Service available:<br>1. R2 Suroboyo Bus bound for Purabaya<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.68952, -7.276560000000002, 0] },
      properties: {
        fid: 36,
        Name: "Pasar Modern Darmo Permai 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.68872, -7.259950000000001, 0] },
      properties: {
        fid: 37,
        Name: "Samsat Tandes 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.688796, -7.259741000000002, 0] },
      properties: {
        fid: 38,
        Name: "Samsat Tandes 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6829, -7.237189999999998, 0] },
      properties: {
        fid: 39,
        Name: "Margomulyo 2",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6823, -7.237180000000005, 0] },
      properties: {
        fid: 40,
        Name: "Margomulyo 1",
        descriptio: "",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6543867, -7.217669700000009, 0] },
      properties: {
        fid: 41,
        Name: "Tambak Oso Wilangun (TOW)",
        descriptio:
          "Terminus for R7 and R8 Suroboyo Bus.<br><br>(This T.O.W. pin-point is the approximate location, the exact location may be different.)<br><br>There is extension service to Romokalisari Adventure Land which runs every weekend. (going further north).",
        timestamp: "",
        begin: "",
        end: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
  ],
};
