var ht_14 = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.73785, -7.298909999999996] },
      properties: {
        fid: 15,
        Name: "Halte Joyoboyo 2",
        descriptio: "Service available:<br>1. R2 Suroboyo Bus bound for Purabaya<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 35,
        Name_2: "Halte Joyoboyo 2",
        descript_1: "Service available:<br>1. R2 Suroboyo Bus bound for Purabaya<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.7394435, -7.29615480000001] },
      properties: {
        fid: 17,
        Name: "Halte Marmoyo",
        descriptio: "Service available:<br>1. R2 Suroboyo Bus bound for Purabaya<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 34,
        Name_2: "Halte Marmoyo",
        descript_1: "Service available:<br>1. R2 Suroboyo Bus bound for Purabaya<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
  ],
};
