var ht_24 = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6744107, -7.306761600000001] },
      properties: {
        fid: 7,
        Name: "Halte Babatan 2",
        descriptio: "Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 25,
        Name_2: "Halte Babatan 2",
        descript_1: "Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6753578, -7.298334300000003] },
      properties: {
        fid: 8,
        Name: "Halte UNESA",
        descriptio:
          "Universitas Negeri Surabaya, CitraLand Gate, National Hospital.<br>Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 26,
        Name_2: "Halte UNESA",
        descript_1:
          "Universitas Negeri Surabaya, CitraLand Gate, National Hospital.<br>Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67571380000001, -7.298327600000009] },
      properties: {
        fid: 9,
        Name: "Halte UNESA 2",
        descriptio:
          "Universitas Negeri Surabaya, CitraLand Gate, National Hospital, Blvd. Famili Selatan.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R8",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 27,
        Name_2: "Halte UNESA 2",
        descript_1:
          "Universitas Negeri Surabaya, CitraLand Gate, National Hospital, Blvd. Famili Selatan.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R8",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67608, -7.2927500000000105] },
      properties: {
        fid: 10,
        Name: "Halte Graha Family",
        descriptio:
          "Plaza Graha Famili, Loop, Sekolah Petra 1.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 29,
        Name_2: "Halte Graha Famili 2",
        descript_1:
          "Plaza Graha Famili, Loop, Sekolah Petra 1.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.675693, -7.292597899999993] },
      properties: {
        fid: 11,
        Name: "Halte Graha Famili",
        descriptio:
          "Services available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo) stops here.",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 28,
        Name_2: "Halte Graha Famili 1",
        descript_1:
          "Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo)<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R7 Suroboyo Bus bound for PTC & Lenmarc (Jono Soewojo) stops here.<",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.67723000000001, -7.288350000000002] },
      properties: {
        fid: 12,
        Name: "Halte PTC",
        descriptio:
          "Pakuwon Mall, PTC, Spazio.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for Lenmarc (Jono Soewojo)",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 30,
        Name_2: "Halte PTC",
        descript_1:
          "Pakuwon Mall, PTC, Spazio.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus bound for Lenmarc (Jono Soewojo)",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6776844, -7.288790400000004] },
      properties: {
        fid: 13,
        Name: "Halte PTC 2",
        descriptio:
          "Spazio, PTC, Pakuwon Mall.<br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo<br><br>IMPORTANT NOTICE:<br>As of 12 August 2022, R8 Suroboyo Bus bound for Joyoboyo stops here.<br>You can transfe",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 31,
        Name_2: "Halte PTC 2",
        descript_1:
          "Spazio, PTC, Pakuwon Mall.<br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo<br><br>IMPORTANT NOTICE: <br>As of 12 August 2022, R8 Suroboyo Bus bound for Joyoboyo stops here.<br>You can trans",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.68105, -7.284729999999998] },
      properties: {
        fid: 14,
        Name: "Halte Jono Soewojo",
        descriptio:
          "Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus (Last stop). After this stop the bus will be continued to be R8 bound for Joyoboyo. You can stay on board.",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 32,
        Name_2: "Halte Jono Soewojo",
        descript_1:
          "Service available:<br>1. TB-II Trans Semanggi bound for ITS & Kejawan Putih<br>2. R7 Suroboyo Bus (Last stop). After this stop the bus will be continued to be R8 bound for Joyoboyo. You can stay on board.",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
    {
      type: "Feature",
      geometry: { type: "Point", coordinates: [112.6813879, -7.284939799999993] },
      properties: {
        fid: 15,
        Name: "Halte Jono Soewojo 2",
        descriptio:
          "Lenmarc Mall, Bukit Darmo Golf, Adhiwangsa Apartment.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp: "",
        begin: "",
        end: "",
        fid_2: 33,
        Name_2: "Halte Jono Soewojo 2",
        descript_1:
          "Lenmarc Mall, Bukit Darmo Golf, Adhiwangsa Apartment.<br><br>Service available:<br>1. TB-II Trans Semanggi bound for Lidah Wetan<br>2. R8 Suroboyo Bus bound for Joyoboyo",
        timestamp_: "",
        begin_2: "",
        end_2: "",
        altitudeMo: "",
        tessellate: -1,
        extrude: 0,
        visibility: -1,
        drawOrder: null,
        icon: "",
      },
    },
  ],
};
